version: '3'
services:
  pre-watch:
    build: . 
    container_name: pre-watch
    environment:
      - OV_VERSION=2
    restart: always
    logging:
      options:
        max-file: '10'
        max-size: '50m'