oversight:
  version: PW_OV_VERSION
  host: PW_OV_HOST
  port: PW_OV_PORT
mongo:
  host: PW_MONGO_DATABASE_IP
  port: PW_MONGO_DATABASE_PORT
  user: PW_MONGO_DATABASE_USER
  password: PW_MONGO_DATABASE_PWD
  db: PW_MONGO_DATABASE_DBNAME

externalplugins: PW_EXTERNAL_PLUGINS
interval: PW_PROCESS_INTERVAL
max_threads: PW_MAX_THREADS