oversight:
  version: 1
  host: "127.0.0.1"
  port: 4321
mongo:
  host: '127.0.0.1'
  port: 27017
  user: oversightUser
  password: somesecretpassword
  db: 'oversight'

externalplugins:
interval: 5
max_threads: 8