oversight:
  version: 3.2
  host: "127.0.0.1"
  port: 4321
mongo:
  host: '127.0.0.1'
  port: 27017
  user: oversightUser
  password: somesecretpassword
  db: 'oversight'
influx:
  host: '127.0.0.1'
  port: 8086
  user: admin
  password: P@ssword1
  db: 'monitoring'
influx2:
  host: '127.0.0.1'
  port: 8086
  token: 'qPEICHzrHp9Ak83A8GzpBUcrVqtAK9V9a1uYnPgfg21ZZSn5hgAmBGNj_h0Un7rBKn4eia2z-tKPEzdootszVg=='
  org: 'my-org'
  bucket: 'my-bucket'

externalplugins:
max_threads: 8